#!/bin/sh
# Xsetup - Script de inicialização do Display Manager

# 1. Garante que qualquer configuração padrão do sistema também seja carregada
if [ -e /usr/share/sddm/scripts/Xsetup ]; then
    . /usr/share/sddm/scripts/Xsetup
fi

# 2. Configura Energia do Monitor (DPMS)
# Sintaxe: xset dpms [standby] [suspend] [off]
# Abaixo: 0 (desativado), 0 (desativado), 600 (desliga em 10 minutos/600s)
/usr/bin/xset dpms 0 0 600