# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kinoite-amd
description: "Customized Fedora Kinoite image (AMD/Virt/Multimedia)"
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - from-file: common-repos.yml
  - from-file: common-packages.yml
  - from-file: common-flatpaks.yml
  # - from-file: common-systemd.yml
  - from-file: common-kvm-libvirt.yml
  - from-file: common-kargs.yml

  - type: signing
