# config/recipe.yml

name: kinoite-custom
description: Fedora Kinoite Customizado (AMD/Virt/Dev)
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  # 1. Copia arquivos locais (Repos e Justfile) para a imagem
  - type: files
    files:
      - source: files/etc/yum.repos.d
        destination: /etc/yum.repos.d/
      - source: files/usr/share/ublue-os/just
        destination: /usr/share/ublue-os/just/

  # 2. Gerenciamento de Pacotes (Substitui seus scripts de install/remove)
  - type: rpm-ostree
    # O que remover (Seu script 02-bloat)
    remove:
      # - firefox
      # - firefox-langpacks
      # - fedora-flathub-remote
      # - plasma-welcome-fedora
      # - fedora-bookmarks
      # - fedora-chromium-config
      # - fedora-chromium-config-kde
      # Removemos ferramentas de guest pois você é o HOST
      # - open-vm-tools-desktop
      # - open-vm-tools
      # - qemu-guest-agent
      # - spice-vdagent
      # - virtualbox-guest-additions
      # Codecs Free (para substituição)
      # - libavcodec-free
      # - libavdevice-free
      # - libavfilter-free
      # - libavformat-free
      # - libavutil-free
      # - libpostproc-free
      # - libswresample-free
      # - libswscale-free
      # - fdk-aac-free

    # O que instalar (Seus scripts 03 e 04 + Navegadores Oficiais)
    install:
      # --- Navegadores Oficiais (RPMs) ---
      - code # VS Code
      - google-chrome-stable
      - brave-browser

      # --- Multimídia Full (RPM Fusion já vem habilitado no uBlue base) ---
      - ffmpeg
      - ffmpeg-libs
      - fdk-aac
      - ffmpegthumbnailer
      - libavcodec-freeworld
      - mesa-va-drivers-freeworld
      - mesa-vdpau-drivers-freeworld
      - pipewire-codec-aptx
      # GStreamer
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-ugly
      - gstreamer1-vaapi
      - gstreamer1-plugin-openh264

      # --- Virtualização e Dev ---
      - qemu-kvm
      - libvirt
      - libvirt-client
      - virt-install
      - virt-manager
      - edk2-ovmf
      - swtpm
      - bridge-utils
      - guestfs-tools
      - libguestfs-tools
      - distrobox
      - zsh
      - htop
      - nvtop
      - fzf
      - zstd

  # 3. Habilitar Serviços (Systemd)
  - type: systemd
    system:
      enabled:
        - libvirtd

  # 4. Argumentos de Kernel (Seu script 05)
  - type: script
    scripts:
      - post-install.sh # Script auxiliar para kargs complexos se necessário,
        # mas o uBlue recomenda usar o módulo 'kargs' se disponível
        # ou bootc. Para simplificar, usamos kargs abaixo:

  - type: kargs
    args:
      - amd_iommu=on
      - iommu=pt
      - kvm_amd.npt=1
      - kvm_amd.avic=1
      - kvm_amd.nested=1
      - kvm_amd.sev=1
      - transparent_hugepage=madvise
